# Your default account ID and workspace ID [flag 1]
# Note these can be also be declared with command flag -a or -w followed by account id or workspace id respectively
# Use --ac or --ws if you want to use these values by default[flag 1]
accountId: 1195941
workspaceId: 1226630
teamId: "521ebb8f-b137-438a-8f2d-c5b7d66bb68e"